import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import type { Campaign, CampaignDraft } from "./types";
import { supabase } from "./supabase";
import { createCampaign, disconnectGmail, getGmailConnection, getRecipients, getTemplate, listCampaigns, queueGeneration, saveRecipients, sendEmail, startGmailConnection, uploadTemplate } from "./api";

type Step = "upload" | "fields" | "recipients" | "preview" | "generate" | "email" | "review" | "manage";
type Field = { id: string; name: string; x: number; y: number; size: number; color: string; bold: boolean };
type Recipient = { id: string; name: string; address: string; college: string; achievement: string; valid: boolean; duplicate: boolean; certificate: "Pending" | "Generated" | "Failed"; email: "Not sent" | "Sent" | "Failed" };

const templateFallback = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1400' height='990'%3E%3Crect width='1400' height='990' fill='%23fbfcf7'/%3E%3Crect x='35' y='35' width='1330' height='920' rx='8' fill='none' stroke='%23bad49d' stroke-width='8'/%3E%3Ctext x='700' y='250' text-anchor='middle' font-family='Georgia' font-size='30' fill='%237c9a5e' letter-spacing='7'%3ECERTIFICATE OF ACHIEVEMENT%3C/text%3E%3Ctext x='700' y='365' text-anchor='middle' font-family='Georgia' font-size='20' fill='%2352684f'%3EThis certificate is proudly presented to%3C/text%3E%3C/svg%3E";
const starters: Campaign[] = [{ id: "sample", name: "Spring Design Workshop", organization: "Northstar University", status: "Draft", updatedAt: "Today", recipients: 0 }];
const defaultFields: Field[] = [{ id: "name", name: "NAME", x: 50, y: 49, size: 34, color: "#18382A", bold: true }, { id: "achievement", name: "ACHIEVEMENT", x: 50, y: 62, size: 17, color: "#38664b", bold: false }];
type SavedWorkspace = { step: Step; template: string | null; fileName: string; fields: Field[]; recipients: Recipient[]; selectedRecipient: string; subject: string; body: string; testSent: boolean };
const workspaceKey = (campaignId: string) => `certifyflow.workspace.${campaignId}`;
const activeCampaignKey = "certifyflow.active-campaign";
function loadWorkspace(campaignId: string): SavedWorkspace | null { try { const value = localStorage.getItem(workspaceKey(campaignId)); return value ? JSON.parse(value) as SavedWorkspace : null; } catch { return null; } }
const sample = (): Recipient[] => [
  ["Rahul Sharma", "rahul@example.edu", "Northstar University", "Design Excellence"], ["Priya Kapoor", "priya@example.edu", "Northstar University", "Outstanding Participant"], ["Arjun Mehta", "arjun@example.edu", "Crescent College", "Innovation Award"],
].map(([name, address, college, achievement]) => ({ id: crypto.randomUUID(), name, address, college, achievement, valid: true, duplicate: false, certificate: "Pending" as const, email: "Not sent" as const } as unknown as Recipient));
const allSteps: { key: Step; label: string }[] = [{ key: "upload", label: "Template" }, { key: "fields", label: "Fields" }, { key: "recipients", label: "Recipients" }, { key: "preview", label: "Preview" }, { key: "generate", label: "Generate" }, { key: "email", label: "Email" }, { key: "review", label: "Send" }];
const isPersistedCampaign = (id: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id);

export function App() {
  if (!supabase) return <AuthUnavailable />;
  return <AuthenticatedApp />;
}

function AuthUnavailable() {
  return <main className="auth-shell"><section className="auth-card"><span className="brand-mark">C</span><h1>Connect CertifyFlow</h1><p className="muted">Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to the frontend environment before starting the app.</p></section></main>;
}

function AuthenticatedApp() {
  const [session, setSession] = useState<import("@supabase/supabase-js").Session | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    supabase!.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false); });
    const { data } = supabase!.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession));
    return () => data.subscription.unsubscribe();
  }, []);
  if (loading) return <main className="auth-shell"><p className="muted">Loading your workspace...</p></main>;
  if (!session) return <AuthForm />;
  return <WorkspaceApp userEmail={session.user.email || ""} />;
}

function AuthForm() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setMessage(""); const { error } = await supabase!.auth.signInWithPassword({ email, password }); setMessage(error?.message || "Signed in."); setPending(false); };
  const signup = async () => { setPending(true); setMessage(""); const { error } = await supabase!.auth.signUp({ email, password }); setMessage(error?.message || "Check your email to confirm your account."); setPending(false); };
  return <main className="auth-shell"><form className="auth-card" onSubmit={submit}><span className="brand-mark">C</span><h1>Sign in to CertifyFlow</h1><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="primary" disabled={pending}>{pending ? "Working..." : "Sign in"}</button><button className="text-button" type="button" disabled={pending} onClick={signup}>Create an account</button>{message && <p className="muted">{message}</p>}</form></main>;
}

function WorkspaceApp({ userEmail }: { userEmail: string }) {
  const [page, setPage] = useState<"dashboard" | "create" | "workspace">("dashboard"); const [campaigns, setCampaigns] = useState(starters); const [campaign, setCampaign] = useState<Campaign | null>(null);
  const [draft, setDraft] = useState<CampaignDraft>({ name: "", organization: "", description: "" }); const [step, setStep] = useState<Step>("upload"); const [template, setTemplate] = useState<string | null>(null); const [fileName, setFileName] = useState(""); const [error, setError] = useState("");
  const [fields, setFields] = useState<Field[]>(defaultFields); const [selected, setSelected] = useState("name");
  const [recipients, setRecipients] = useState<Recipient[]>([]); const [selectedRecipient, setSelectedRecipient] = useState(""); const [generating, setGenerating] = useState(false); const [connected, setConnected] = useState(false); const [testSent, setTestSent] = useState(false); const [sending, setSending] = useState(false); const [subject, setSubject] = useState("Congratulations {{NAME}}!"); const [body, setBody] = useState("Hello {{NAME}},\n\nCongratulations on completing {{EVENT_NAME}}.\n\nPlease find your certificate attached.\n\nRegards,\n{{ORGANIZATION_NAME}}");
  useEffect(() => { listCampaigns().then(setCampaigns).catch((reason: Error) => setError(reason.message)); getGmailConnection().then(({ connected }) => setConnected(connected)).catch(() => undefined); }, []);
  useEffect(() => { if (campaign || page !== "dashboard" || !campaigns.length) return; try { const activeId = localStorage.getItem(activeCampaignKey); const active = campaigns.find((item) => item.id === activeId); if (active) void open(active); } catch { /* Browser storage may be unavailable. */ } }, [campaigns, campaign, page]);
  useEffect(() => { if (!campaign || campaign.id === "sample") return; try { localStorage.setItem(workspaceKey(campaign.id), JSON.stringify({ step, template: null, fileName, fields, recipients, selectedRecipient, subject, body, testSent } satisfies SavedWorkspace)); } catch (reason) { setError(reason instanceof Error ? "Your browser storage is full. The campaign is still saved to the server." : "Could not save this campaign locally."); } }, [campaign, step, template, fileName, fields, recipients, selectedRecipient, subject, body, testSent]);
  const disconnect = async () => { try { await disconnectGmail(); setConnected(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not disconnect Gmail."); } };
  const create = async (e: FormEvent) => { e.preventDefault(); if (!draft.name.trim() || !draft.organization.trim()) return; try { const c = await createCampaign({ ...draft, name: draft.name.trim(), organization: draft.organization.trim() }); localStorage.setItem(activeCampaignKey, c.id); setCampaign(c); setCampaigns((list) => [c, ...list]); setStep("upload"); setPage("workspace"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create the campaign."); } };
  const open = async (c: Campaign) => { localStorage.setItem(activeCampaignKey, c.id); const saved = loadWorkspace(c.id); setCampaign(c); setRecipients(saved?.recipients || []); setSelectedRecipient(saved?.selectedRecipient || ""); setStep(saved?.step || "upload"); setTemplate(saved?.template || null); setFileName(saved?.fileName || ""); setFields(saved?.fields || defaultFields); setSubject(saved?.subject || "Congratulations {{NAME}}!"); setBody(saved?.body || "Hello {{NAME}},\n\nCongratulations on completing {{EVENT_NAME}}.\n\nPlease find your certificate attached.\n\nRegards,\n{{ORGANIZATION_NAME}}"); setTestSent(saved?.testSent || false); setPage("workspace"); if (isPersistedCampaign(c.id)) { if (!saved?.recipients?.length) try { const result = await getRecipients(c.id); const restored = result.recipients.map((recipient) => ({ id: recipient.id, name: recipient.data.name || "Recipient", address: recipient.email, college: recipient.data.college || "", achievement: recipient.data.achievement || "Participant", valid: recipient.is_valid, duplicate: false, certificate: "Pending" as const, email: "Not sent" as const })); setRecipients(restored); setSelectedRecipient(restored[0]?.id || ""); } catch { setError("Could not restore recipients from the server."); } if (!saved?.template) try { const result = await getTemplate(c.id); setTemplate(result.url); setFileName("Saved certificate template"); } catch { /* A template may not exist for a new campaign yet. */ } } };
  const choose = async (f?: File) => { setError(""); if (!f) return; if (!["image/png", "image/jpeg"].includes(f.type)) return setError("Choose a PNG or JPG image."); if (f.size > 10 * 1024 * 1024) return setError("Template must be 10 MB or smaller."); setTemplate(URL.createObjectURL(f)); setFileName(f.name); if (campaign) try { await uploadTemplate(campaign.id, f); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not upload the template."); } };
  const importCsv = (f?: File) => { if (!f || !campaign) return; const read = new FileReader(); read.onload = async () => { const rows = String(read.result).trim().split(/\r?\n/).map((x) => x.split(",").map((v) => v.trim())); if (rows.length < 2) return setError("CSV needs a header row and at least one recipient."); const h = rows[0].map((x) => x.toLowerCase()); const at = (key: string) => h.findIndex((x) => x.includes(key)); const emailAt = at("email"), nameAt = at("name"), collegeAt = at("college"), awardAt = at("achievement"); const seen = new Set<string>(); const result = rows.slice(1).filter((row) => row.some(Boolean)).map((row, i) => { const address = row[emailAt] || ""; const duplicate = seen.has(address.toLowerCase()); seen.add(address.toLowerCase()); return { id: crypto.randomUUID(), name: row[nameAt] || `Recipient ${i + 1}`, address, college: row[collegeAt] || "", achievement: row[awardAt] || "Participant", valid: /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address), duplicate, certificate: "Pending" as const, email: "Not sent" as const } as unknown as Recipient; }); setRecipients(result); setSelectedRecipient(result[0]?.id || ""); try { await saveRecipients(campaign.id, result.filter((recipient) => recipient.valid && !recipient.duplicate).map((recipient) => ({ name: recipient.name, email: recipient.address, college: recipient.college, achievement: recipient.achievement }))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save recipients."); } }; read.readAsText(f); };
  const generated = recipients.filter((r) => r.certificate === "Generated").length; const ready = recipients.filter((r) => r.valid && !r.duplicate); const sent = recipients.filter((r) => r.email === "Sent").length;
  const generate = async () => { if (!campaign) return; if (isPersistedCampaign(campaign.id)) try { await queueGeneration(campaign.id); } catch (reason) { return setError(reason instanceof Error ? reason.message : "Could not queue generation."); } setGenerating(true); ready.forEach((r, i) => setTimeout(() => { setRecipients((all) => all.map((x) => x.id === r.id ? { ...x, certificate: "Generated" } : x)); if (i === ready.length - 1) setGenerating(false); }, 300 * (i + 1))); };
  const selectedData = recipients.find((r) => r.id === selectedRecipient) || ready[0];
  const sendTest = async () => { if (!campaign || !selectedData) return; setSending(true); setError(""); try { const certificate = await renderCertificate(template || templateFallback, fields, campaign, selectedData); await sendEmail({ subject: interpolate(subject, selectedData, campaign), body: interpolate(body, selectedData, campaign), fileName: safeFileName(`${selectedData.name}-certificate.png`), certificateBase64: await blobToBase64(certificate) }); setTestSent(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not send the test email."); } finally { setSending(false); } };
  const deliver = async (targets: Recipient[]) => { if (!campaign) return; setSending(true); setError(""); for (const recipient of targets) { try { const certificate = await renderCertificate(template || templateFallback, fields, campaign, recipient); await sendEmail({ to: recipient.address, subject: interpolate(subject, recipient, campaign), body: interpolate(body, recipient, campaign), fileName: safeFileName(`${recipient.name}-certificate.png`), certificateBase64: await blobToBase64(certificate) }); setRecipients((all) => all.map((x) => x.id === recipient.id ? { ...x, email: "Sent" } : x)); } catch (reason) { setRecipients((all) => all.map((x) => x.id === recipient.id ? { ...x, email: "Failed" } : x)); setError(reason instanceof Error ? reason.message : "One or more emails could not be sent."); } } setSending(false); };
  const send = async () => deliver(ready);
  const retry = async () => deliver(recipients.filter((recipient) => recipient.email === "Failed"));
  const downloadAll = async () => {
    const files = await Promise.all(recipients.filter((r) => r.certificate === "Generated").map(async (recipient) => ({ name: safeFileName(`${recipient.name}-certificate.png`), bytes: new Uint8Array(await (await renderCertificate(template || templateFallback, fields, campaign!, recipient)).arrayBuffer()) })));
    if (!files.length) return;
    const url = URL.createObjectURL(makeZip(files)); const link = document.createElement("a"); link.href = url; link.download = safeFileName(`${campaign?.name || "certificates"}.zip`); link.click(); URL.revokeObjectURL(url);
  };
  return <div className="app-shell"><aside className="sidebar"><button className="brand" onClick={() => setPage("dashboard")}><span className="brand-mark">C</span>CertifyFlow</button><nav><button className={page === "dashboard" ? "nav-item selected" : "nav-item"} onClick={() => setPage("dashboard")}>▦ Dashboard</button><button className="nav-item" onClick={() => { setDraft({ name: "", organization: "", description: "" }); setError(""); setPage("create"); }}>＋ New campaign</button></nav><div className="sidebar-footer"><div className="profile"><span className="avatar">{userEmail.slice(0, 2).toUpperCase()}</span><span><strong>{userEmail}</strong><button className="text-button" onClick={() => supabase!.auth.signOut()}>Sign out</button></span></div></div></aside><main className="main-content">{page === "dashboard" && <Dashboard campaigns={campaigns} onCreate={() => { setError(""); setPage("create"); }} onOpen={open} />}{page === "create" && <Create draft={draft} setDraft={setDraft} error={error} onCancel={() => setPage("dashboard")} onSubmit={create} />}{page === "workspace" && campaign && <Workspace c={campaign} step={step} setStep={setStep} template={template} fileName={fileName} error={error} choose={choose} fields={fields} setFields={setFields} selected={selected} setSelected={setSelected} recipients={recipients} setRecipients={setRecipients} importCsv={importCsv} selectedData={selectedData} setSelectedRecipient={setSelectedRecipient} generated={generated} ready={ready} generating={generating} generate={generate} connected={connected} setConnected={setConnected} testSent={testSent} setTestSent={setTestSent} testEmail={sendTest} sending={sending} send={send} retry={retry} sent={sent} subject={subject} setSubject={setSubject} body={body} setBody={setBody} downloadAll={downloadAll} disconnect={disconnect} />}</main></div>;
}
function Dashboard({ campaigns, onCreate, onOpen }: { campaigns: Campaign[]; onCreate: () => void; onOpen: (c: Campaign) => void }) { return <><header className="topbar"><div><p className="eyebrow">WORKSPACE</p><h1>Good morning, Alex</h1><p className="muted">Create, personalize, and send certificates with confidence.</p></div><button className="primary" onClick={onCreate}>＋ Create campaign</button></header><section className="stats"><Card label="Total campaigns" value={campaigns.length} /><Card label="Certificates sent" value={campaigns.filter((c) => c.status === "Completed").reduce((n, c) => n + c.recipients, 0)} /><Card label="Active campaigns" value={0} /></section><section className="panel"><div className="section-head"><div><h2>Recent campaigns</h2><p className="muted">Pick up where you left off.</p></div></div><div className="campaign-list">{campaigns.map((c) => <button className="campaign-row" key={c.id} onClick={() => onOpen(c)}><span className="campaign-icon">✦</span><span className="campaign-meta"><strong>{c.name}</strong><small>{c.organization} · Updated {c.updatedAt}</small></span><span className="recipient-count">{c.recipients} recipients</span><span className="status draft">{c.status}</span><span className="arrow">›</span></button>)}</div></section></>; }
function Card({ label, value }: { label: string; value: number }) { return <article className="stat-card"><p>{label}</p><strong>{value}</strong><small>All time</small></article>; }
function Create({ draft, setDraft, error, onCancel, onSubmit }: { draft: CampaignDraft; setDraft: (v: CampaignDraft) => void; error: string; onCancel: () => void; onSubmit: (e: FormEvent) => void }) { return <div className="wizard"><button className="back-link" onClick={onCancel}>← Back to dashboard</button><h1>Create a campaign</h1><p className="muted wizard-subtitle">Start with a few details. You can change these later.</p><form className="form-card" onSubmit={onSubmit}><label>Campaign name<input required autoFocus value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label>Organization name<input required value={draft.organization} onChange={(e) => setDraft({ ...draft, organization: e.target.value })} /></label><label>Short description <span className="optional">Optional</span><textarea rows={3} value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label>{error && <p className="error">{error}</p>}<div className="form-actions"><button className="secondary" type="button" onClick={onCancel}>Cancel</button><button className="primary">Continue to template →</button></div></form></div>; }
type Props = { c: Campaign; step: Step; setStep: (s: Step) => void; template: string | null; fileName: string; error: string; choose: (f?: File) => void; fields: Field[]; setFields: (f: Field[]) => void; selected: string; setSelected: (id: string) => void; recipients: Recipient[]; setRecipients: (r: Recipient[]) => void; importCsv: (f?: File) => void; selectedData?: Recipient; setSelectedRecipient: (id: string) => void; generated: number; ready: Recipient[]; generating: boolean; generate: () => void; connected: boolean; setConnected: (v: boolean) => void; disconnect: () => Promise<void>; testSent: boolean; setTestSent: (v: boolean) => void; testEmail: () => Promise<void>; sending: boolean; send: () => Promise<void>; retry: () => Promise<void>; sent: number; subject: string; setSubject: (s: string) => void; body: string; setBody: (s: string) => void; downloadAll: () => Promise<void> };
function Workspace(p: Props) { const current = allSteps.findIndex((s) => s.key === p.step); return <><header className="campaign-header"><div><button className="back-link" onClick={() => history.back()}>← Dashboard</button><h1>{p.c.name}</h1><p className="muted">{p.c.organization}</p></div><button className="secondary" onClick={() => p.setStep("manage")}>Manage recipients</button></header><div className="stepper">{allSteps.map((s, i) => <button key={s.key} className={s.key === p.step ? "current" : i < current ? "done" : ""} onClick={() => p.setStep(s.key)}><span>{i < current ? "✓" : i + 1}</span>{s.label}</button>)}</div>{p.step === "upload" && <Upload p={p} />}{p.step === "fields" && <Fields p={p} />}{p.step === "recipients" && <Recipients p={p} />}{p.step === "preview" && <Preview p={p} />}{p.step === "generate" && <Generate p={p} />}{p.step === "email" && <Email p={p} />}{p.step === "review" && <Review p={p} />}{p.step === "manage" && <Manage p={p} />}</>; }
function Next({ p, to, disabled, text }: { p: Props; to: Step; disabled?: boolean; text: string }) { return <div className="workflow-actions"><button className="primary" disabled={disabled} onClick={() => p.setStep(to)}>{text} →</button></div>; }
function Upload({ p }: { p: Props }) { const ref = useRef<HTMLInputElement>(null); return <section className="workflow-card"><h2>Upload certificate template</h2><p className="muted">Use a high-resolution landscape PNG or JPG. Your original file remains private.</p><input className="sr-only" ref={ref} type="file" accept="image/png,image/jpeg" onChange={(e) => p.choose(e.target.files?.[0])} />{p.template ? <div className="template-preview"><img src={p.template} alt="Certificate template" /><div className="file-bar">✓ <strong>{p.fileName}</strong><button onClick={() => ref.current?.click()}>Replace image</button></div></div> : <button className="dropzone" onClick={() => ref.current?.click()}><span className="upload-glyph">↑</span><strong>Upload certificate template</strong><span>Drag and drop, or browse your files</span><small>PNG or JPG · Up to 10 MB</small></button>}{p.error && <p className="error">{p.error}</p>}<Next p={p} to="fields" disabled={!p.template} text="Set up fields" /></section>; }
function Canvas({ p, recipient }: { p: Props; recipient?: Recipient }) { return <div className="certificate-canvas"><img src={p.template || templateFallback} alt="Certificate preview" />{p.fields.map((f) => <button key={f.id} className={p.selected === f.id ? "certificate-field selected" : "certificate-field"} onClick={() => p.setSelected(f.id)} style={{ left: `${f.x}%`, top: `${f.y}%`, fontSize: `${Math.max(10, f.size / 3)}px`, color: f.color, fontWeight: f.bold ? 700 : 400 }}>{recipient ? value(f.name, recipient, p.c) : `{{${f.name}}}`}</button>)}</div>; }
function value(name: string, r: Recipient, c: Campaign) { const x: Record<string, string> = { NAME: r.name, EMAIL: (r as any).address, COLLEGE: r.college, ACHIEVEMENT: r.achievement, EVENT_NAME: c.name, ORGANIZATION_NAME: c.organization, DATE: new Date().toLocaleDateString() }; return x[name] || `{{${name}}}`; }
function Fields({ p }: { p: Props }) { const f = p.fields.find((x) => x.id === p.selected)!; const update = (patch: Partial<Field>) => p.setFields(p.fields.map((x) => x.id === f.id ? { ...x, ...patch } : x)); return <section className="editor-layout"><div className="workflow-card canvas-card"><div className="section-head"><div><h2>Place dynamic fields</h2><p className="muted">Click a field to edit it. Position values create consistent certificate output.</p></div><button className="secondary" onClick={() => { const n = { id: crypto.randomUUID(), name: `CUSTOM_${p.fields.length + 1}`, x: 50, y: 72, size: 16, color: "#18382A", bold: false }; p.setFields([...p.fields, n]); p.setSelected(n.id); }}>＋ Add field</button></div><Canvas p={p} /></div><aside className="properties"><h3>Field properties</h3><label>Variable<input value={f.name} onChange={(e) => update({ name: e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g, "_") })} /></label><label>Horizontal (%)<input type="number" min="0" max="100" value={f.x} onChange={(e) => update({ x: Number(e.target.value) })} /></label><label>Vertical (%)<input type="number" min="0" max="100" value={f.y} onChange={(e) => update({ y: Number(e.target.value) })} /></label><label>Font size<input type="number" min="8" max="80" value={f.size} onChange={(e) => update({ size: Number(e.target.value) })} /></label><label>Color<input type="color" value={f.color} onChange={(e) => update({ color: e.target.value })} /></label><button className={f.bold ? "format active" : "format"} onClick={() => update({ bold: !f.bold })}><b>B</b> Bold</button>{p.fields.length > 1 && <button className="danger-link" onClick={() => { p.setFields(p.fields.filter((x) => x.id !== f.id)); p.setSelected(p.fields[0].id); }}>Delete field</button>}</aside><Next p={p} to="recipients" text="Continue to recipients" /></section>; }
function Recipients({ p }: { p: Props }) { const ref = useRef<HTMLInputElement>(null); const valid = p.ready.length; const useSample = () => { const r = sample(); p.setRecipients(r); p.setSelectedRecipient(r[0].id); }; return <section className="workflow-card"><div className="section-head"><div><h2>Add recipients</h2><p className="muted">Upload a CSV with Name, Email, College, and Achievement columns.</p></div><input className="sr-only" ref={ref} type="file" accept=".csv,text/csv" onChange={(e) => p.importCsv(e.target.files?.[0])} /><button className="secondary" onClick={() => ref.current?.click()}>Upload CSV</button></div>{!p.recipients.length ? <div className="empty-state"><strong>No recipient data yet</strong><p>Import your list or explore the flow using sample recipients.</p><button className="primary" onClick={useSample}>Use sample recipients</button></div> : <><div className="validation-grid"><span><b>{p.recipients.length}</b>Total rows</span><span className="good"><b>{valid}</b>Valid emails</span><span className="bad"><b>{p.recipients.filter((r) => !r.valid).length}</b>Invalid emails</span><span className="bad"><b>{p.recipients.filter((r) => r.duplicate).length}</b>Duplicates</span></div><RecipientTable rows={p.recipients} /></>}<Next p={p} to="preview" disabled={!valid} text="Preview certificates" /></section>; }
function RecipientTable({ rows }: { rows: Recipient[] }) { return <div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>College</th><th>Validation</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.name}</td><td>{(r as any).address}</td><td>{r.college || "—"}</td><td>{r.duplicate ? <span className="pill bad">Duplicate</span> : r.valid ? <span className="pill good">Ready</span> : <span className="pill bad">Invalid email</span>}</td></tr>)}</tbody></table></div>; }
function Preview({ p }: { p: Props }) { const r = p.selectedData; return <section className="workflow-card"><h2>Personalized certificate preview</h2><p className="muted">Preview uses the same configuration that will be used for generation.</p><label className="preview-select">Preview recipient<select value={r?.id || ""} onChange={(e) => p.setSelectedRecipient(e.target.value)}>{p.ready.map((x) => <option key={x.id} value={x.id}>{x.name} · {(x as any).address}</option>)}</select></label>{r && <Canvas p={p} recipient={r} />}<Next p={p} to="generate" text="Confirm and generate" /></section>; }
function Generate({ p }: { p: Props }) { return <section className="workflow-card narrow"><h2>Generate certificates</h2><p className="muted">Generation is isolated per recipient: one failure will never stop the rest.</p><div className="summary-box"><span>Eligible recipients <b>{p.ready.length}</b></span><span>Certificates generated <b>{p.generated} / {p.ready.length}</b></span></div>{p.generating && <Progress value={p.generated} total={p.ready.length} />}{p.generated < p.ready.length ? <button className="primary" disabled={p.generating} onClick={p.generate}>{p.generating ? `Generating ${p.generated} / ${p.ready.length}…` : `Generate ${p.ready.length} certificates`}</button> : <><p className="success">✓ All eligible certificates have been generated.</p><p className="muted direct-note">Email delivery is optional. You can manage your generated certificates now or continue to configure email delivery.</p><div className="post-generate-actions"><button className="secondary" onClick={() => p.setStep("manage")}>Finish without email</button><button className="primary" onClick={() => p.setStep("email")}>Configure email →</button></div></>}</section>; }
function Progress({ value, total }: { value: number; total: number }) { return <div className="progress"><i style={{ width: `${total ? value / total * 100 : 0}%` }} /></div>; }
function Email({ p }: { p: Props }) { const invalid = [...p.subject.matchAll(/\{\{([^}]+)\}\}/g), ...p.body.matchAll(/\{\{([^}]+)\}\}/g)].some((x) => !["NAME", "EMAIL", "COLLEGE", "ACHIEVEMENT", "EVENT_NAME", "ORGANIZATION_NAME", "DATE"].includes(x[1])); const connect = async () => { try { const { url } = await startGmailConnection(); window.location.assign(url); } catch (reason) { window.alert(reason instanceof Error ? reason.message : "Could not connect Gmail."); } }; return <section className="email-layout"><section className="workflow-card"><h2>Prepare email delivery</h2><div className={p.connected ? "connection connected" : "connection"}><div><strong>{p.connected ? "Gmail connected" : "Connect Gmail"}</strong><p>{p.connected ? "Your Gmail account is authorized for this campaign." : "Use Gmail OAuth. No password is requested or stored."}</p></div><button className={p.connected ? "secondary" : "primary"} onClick={p.connected ? p.disconnect : connect}>{p.connected ? "Disconnect" : "Connect Gmail"}</button></div><label>Subject<input value={p.subject} onChange={(e) => p.setSubject(e.target.value)} /></label><label>Email body<textarea rows={9} value={p.body} onChange={(e) => p.setBody(e.target.value)} /></label>{invalid && <p className="error">An email contains an unsupported dynamic variable.</p>}{p.error && <p className="error">{p.error}</p>}<div className="form-actions"><button className="secondary" disabled={!p.connected || invalid || p.sending} onClick={p.testEmail}>{p.testSent ? "✓ Test email sent" : p.sending ? "Sending test email..." : "Send test email"}</button><button className="primary" disabled={!p.connected || invalid || p.sending} onClick={() => p.setStep("review")}>Review campaign →</button></div></section><aside className="help-card"><h3>Safe sending</h3><p>A test message is required before bulk delivery. The production API should treat each delivery idempotently to prevent duplicates.</p></aside></section>; }
function Review({ p }: { p: Props }) { const ready = p.connected && p.testSent && p.generated === p.ready.length && p.ready.length > 0; return <section className="workflow-card narrow"><h2>Final campaign review</h2><div className="review-list"><span>Recipients <b>{p.recipients.length}</b></span><span>Valid emails <b>{p.ready.length}</b></span><span>Certificates generated <b>{p.generated} / {p.ready.length}</b></span><span>Gmail account <b>{p.connected ? "Connected" : "Not connected"}</b></span><span>Test email <b>{p.testSent ? "Verified" : "Not sent"}</b></span></div>{!ready && <p className="warning">Complete the required steps before delivery.</p>}{p.sending && <Progress value={p.sent} total={p.ready.length} />}<button className="primary" disabled={!ready || p.sending || p.sent === p.ready.length} onClick={p.send}>{p.sending ? `Sending ${p.sent} / ${p.ready.length}…` : p.sent === p.ready.length ? "Campaign sent" : `Send ${p.ready.length} certificates`}</button><Next p={p} to="manage" text="View delivery status" /></section>; }
function Manage({ p }: { p: Props }) { const failed = p.recipients.filter((r) => r.email === "Failed").length; return <section className="workflow-card"><div className="section-head"><div><h2>Certificate management</h2><p className="muted">Per-recipient certificate and email results.</p></div><div className="manage-actions">{p.generated > 0 && <button className="primary" onClick={p.downloadAll}>Download all (.zip)</button>}{failed > 0 && <button className="secondary" disabled={p.sending} onClick={p.retry}>Retry {failed} failed</button>}</div></div><div className="validation-grid"><span><b>{p.recipients.length}</b>Recipients</span><span className="good"><b>{p.generated}</b>Generated</span><span className="good"><b>{p.sent}</b>Sent</span><span className="bad"><b>{failed}</b>Failed</span></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Certificate</th><th>Email</th></tr></thead><tbody>{p.recipients.map((r) => <tr key={r.id}><td>{r.name}</td><td>{(r as any).address}</td><td><span className="pill good">{r.certificate}</span></td><td><span className={r.email === "Failed" ? "pill bad" : "pill good"}>{r.email}</span></td></tr>)}</tbody></table></div></section>; }

async function renderCertificate(source: string, fields: Field[], campaign: Campaign, recipient: Recipient) {
  const image = new Image(); image.crossOrigin = "anonymous"; image.src = source; await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("Certificate template could not be rendered. Check that the Supabase Storage bucket allows image reads.")); });
  const canvas = document.createElement("canvas"); canvas.width = image.naturalWidth || 1400; canvas.height = image.naturalHeight || 990; const context = canvas.getContext("2d")!; context.drawImage(image, 0, 0, canvas.width, canvas.height);
  fields.forEach((field) => { context.font = `${field.bold ? "700" : "400"} ${Math.round(field.size * canvas.width / 1400)}px Georgia`; context.fillStyle = field.color; context.textAlign = "center"; context.textBaseline = "middle"; context.fillText(value(field.name, recipient, campaign), field.x / 100 * canvas.width, field.y / 100 * canvas.height); });
  return new Promise<Blob>((resolve) => canvas.toBlob((blob) => resolve(blob!), "image/png"));
}
function interpolate(template: string, recipient: Recipient, campaign: Campaign) { return template.replace(/\{\{([^}]+)\}\}/g, (_match, name: string) => value(name, recipient, campaign)); }
async function blobToBase64(blob: Blob) { const bytes = new Uint8Array(await blob.arrayBuffer()); let binary = ""; const chunkSize = 0x8000; for (let index = 0; index < bytes.length; index += chunkSize) binary += String.fromCharCode(...bytes.subarray(index, index + chunkSize)); return btoa(binary); }
function safeFileName(value: string) { return value.replace(/[<>:"/\\|?*]+/g, "-").replace(/\s+/g, "-").toLowerCase(); }
function makeZip(files: { name: string; bytes: Uint8Array }[]) {
  const buffer = (bytes: Uint8Array) => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer; const encoder = new TextEncoder(); const local: ArrayBuffer[] = []; const central: ArrayBuffer[] = []; let offset = 0;
  for (const file of files) { const name = encoder.encode(file.name); const crc = crc32(file.bytes); const head = new Uint8Array(30); const h = new DataView(head.buffer); h.setUint32(0, 0x04034b50, true); h.setUint16(4, 20, true); h.setUint32(14, crc, true); h.setUint32(18, file.bytes.length, true); h.setUint32(22, file.bytes.length, true); h.setUint16(26, name.length, true); local.push(buffer(head), buffer(name), buffer(file.bytes)); const cd = new Uint8Array(46); const d = new DataView(cd.buffer); d.setUint32(0, 0x02014b50, true); d.setUint16(4, 20, true); d.setUint16(6, 20, true); d.setUint32(16, crc, true); d.setUint32(20, file.bytes.length, true); d.setUint32(24, file.bytes.length, true); d.setUint16(28, name.length, true); d.setUint32(42, offset, true); central.push(buffer(cd), buffer(name)); offset += head.length + name.length + file.bytes.length; }
  const centralSize = central.reduce((size, part) => size + part.byteLength, 0); const end = new Uint8Array(22); const e = new DataView(end.buffer); e.setUint32(0, 0x06054b50, true); e.setUint16(8, files.length, true); e.setUint16(10, files.length, true); e.setUint32(12, centralSize, true); e.setUint32(16, offset, true); return new Blob([...local, ...central, buffer(end)], { type: "application/zip" });
}
const crcTable = (() => { const table = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; table[n] = c >>> 0; } return table; })();
function crc32(bytes: Uint8Array) { let c = 0xffffffff; for (const byte of bytes) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; }
